name       : tootle
version    : 0.1.5
release    : 2
source     :
    - https://github.com/bleakgrey/tootle/archive/0.1.5.tar.gz : 77b441df19b4d9f885b95510712f25b5e6719a27cdb527831e03212063df88d1
license    : GPL-3.0-or-later
summary    : GTK+ client for Mastodon
component  : network.clients
description: |
    Tootle is a client for the world’s largest free, open-source, decentralized microblogging network with real-time notifications and multiple accounts support.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(granite)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsoup-2.4)
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
