name        : tootle
version     : 0.1.3
release     : 1
source      :
    - https://github.com/bleakgrey/tootle/archive/0.1.3.tar.gz : d0462237e09f70bfbb19b0ba4f8471b3e6d6a2cb11f6dd8132f095954238e323
license     : GPL-3.0-or-later
summary     : GTK+ client for Mastodon
component   : network.clients
description : |
     Tootle is a client for the world’s largest free, open-source, decentralized microblogging network with real-time notifications and multiple accounts support.
builddeps   :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(granite)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsoup-2.4)
    - vala
setup       : |
    %meson_configure
build       : |
    %ninja_build
install     : |
    %ninja_install
