name       : tootle
version    : 0.1.5
release    : 3
source     :
    - git|https://github.com/bleakgrey/tootle.git : 7b3dbfe7e6aba5f39366ae8e310c965dfd6aa148
license    : GPL-3.0-or-later
summary    : GTK+ client for Mastodon
component  : network.clients
description: |
    Tootle is a client for the world’s largest free, open-source, decentralized microblogging network with real-time notifications and multiple accounts support.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(granite)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsoup-2.4)
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
