name       : tootle
version    : 0.2.0
release    : 6
source     :
    - https://github.com/bleakgrey/tootle/archive/0.2.0.tar.gz : e83c4a0539bf7b4b9d2b81d036ee0e8a69564b11c70f77ded5091955a89d2737
license    : GPL-3.0-or-later
summary    : GTK+ client for Mastodon
component  : network.clients
description: |
    Tootle is a client for the world’s largest free, open-source, decentralized microblogging network with real-time notifications and multiple accounts support.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(granite)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsoup-2.4)
    - vala
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-emblem-favorite-symbolic-for-favoriting.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
